---
repository:
  name: test_repo
  description: Repository for running experiments and tests against
  private: false
  has_issues: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
 
 labels:
  # Custom
  - name: maintenance
    color: E9B864
    description: Regular maintenance tasks
  - name: breaking change
    color: B60205
    description: Change is not backwards compatible
  # Default
  - name: bug
    color: CC0000
    description: Something isn't working
  - name: documentation
    color: 0075CA
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: A2EEEF
    description: New feature or request
  - name: good first issue
    color: 7057FF
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: E4E669
    description: This doesn't seem right
  - name: question
    color: D876E3
    description: Further information is requested
  - name: wontfix
    color: FFFFFF
    description: This will not be worked on

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
