---

name: 'Boolean Input'

inputs:
  my-boolean:
    description: 'Boolean input'
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: 'This should be true'
      shell: bash
      run: echo ${{ github.event.inputs.my-boolean == 'true' }}

    - name: 'This should be false'
      shell: bash
      run: echo ${{ github.event.inputs.my-boolean == true }}
