---
name: 'Run'

inputs:
  node_version:
    description: 'The node version to use'
    type: string
    default: ''
  command:
    description: 'The command to run'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    -
      name: 'Setup'
      uses: mike-carey/test_repo/actions/setup@master
    -
      name: 'Run npm command'
      shell: bash
      run: npm run ${{ inputs.command }}
