---
name: 'Setup'

inputs:
  node_version:
    description: 'The node version to use'
    type: string
    default: ''

runs:
  using: 'composite'
  steps:
    -
      name: 'Checkout'
      uses: actions/checkout@v2
    -
      name: 'Determine node version'
      id: version
      run: ${{ github.action_path }}/setup.sh
      shell: bash
      env:
        NODE_VERSION: ${{ inputs.node_version }}
    -
      name: 'Setup node'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.version.outputs.node_verison }}
    -
      name: 'Install npm dependencies'
      shell: bash
      run: npm ci
