---

name: 'Demonstrates error with installing markdownlint-cli'

on:
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  install:
    name: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dep: [markdownlint-cli, markdownlint-cli2, node]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      - id: install
        run: brew install ${{ matrix.dep }}
        continue-on-error: true

      - run: brew config

      - run: brew doctor
        continue-on-error: true

      - run: brew info ${{ matrix.dep }}

      - name: 'List deps'
        run: brew deps markdownlint-cli
        on: success()
