---

name: 'Demonstrates error with installing markdownlint-cli'

on:
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  install:
    name: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: 'Set up Homebrew'
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew info

      - run: brew doctor

      - run: brew info markdownlint-cli

      - run: brew install markdownlint-cli
