---

name: 'Demonstrates error with installing markdownlint-cli'

on:
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  install:
    name: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      - id: install
        run: brew install markdownlint-cli
        continue-on-error: true

      - run: brew config

      - run: brew doctor
        continue-on-error: true

      - run: brew info markdownlint-cli

      - run: markdownlint-cli
        continue-on-error: true # allow failure so we can still see the outcome of macos-latest

      - name: 'List deps'
        run: brew deps markdownlint-cli
        on: success()
