---

name: 'Reusable Test'
on: [workflow_call]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fail'
        run: exit 1
      
      - if: always()
        run: echo ${{ job.status }}

  job:
    name: 'My job'
    runs-on: ubuntu-latest
    needs:
      - test
    if: always()
    steps:
      - run: echo ${{ job.status }}
