---

name: 'Test'

on: [workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Fail'
        run: exit 1

      - name: 'Status'
        if: always()
        run: echo ${{ job.status }}
