---

name: 'Test'

on: [workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Tests usage of vars from reusable workflows'
    uses: mike-carey/test/.github/workflows/reusable-workflow.yml@main
